## Задачи на строки

### Задача 1.
Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли
некоторая перестановка строки s1 “победить” некоторую перестановку
строки s2 или наоборот.
Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y
[i] (в алфавитном порядке) для всех i от 0 до n-1.

In [2]:
from itertools import permutations


def can_win(s_attack, s_defend):
    for i in range(len(s_attack)):
        if s_attack[i] < s_defend[i]:
            return False
    return True


def all_combinations(s1_origin, s2_origin):
    arr_all_comb1 = [''.join(p) for p in permutations(s1_origin)]
    arr_all_comb2 = [''.join(p) for p in permutations(s2_origin)]
    for s1 in arr_all_comb1:
        for s2 in arr_all_comb2:
            if s1 != s2:
                if can_win(s1, s2) or can_win(s2, s1):
                    return True
    return False

In [3]:
print(all_combinations('abe', 'acc'))
print(all_combinations('abc', 'xya'))

False
True


### Задача 2.
Дана строка s, вернуть самую длинную полиндромную подстроку в s.

In [4]:
def isPalindrome(s):
    return s == s[::-1]


def longest_palindrome(s):
    s_longest_pal = ''
    length = len(s)
    arr_all_substrings = [s[i: j] for i in range(len(s))
           for j in range(i + 1, len(s) + 1)]

    for s1 in arr_all_substrings:
        if isPalindrome(s1):
            if len(s1) > len(s_longest_pal):
                s_longest_pal = s1
    return s_longest_pal

In [5]:
s = 'babad'
print(longest_palindrome(s))
s = 'cbbd'
print(longest_palindrome(s))

bab
bb


### Задача 3.
Вернуть количество отдельных непустых подстрок текста, которые могут
быть записаны как конкатенация некоторой строки с самой собой (т.е. она
может быть записана, как a + a, где a - некоторая строка).

In [6]:
from math import ceil


def concat(s):

    return s == s[:ceil(len(s) / 2)] + s[:ceil(len(s) / 2)]


def all_concat(s):
    dict_of_concat = dict()
    length = len(s)
    arr_all_substrings = [s[i: j] for i in range(length)
           for j in range(i + 1, length + 1)]

    for s1 in arr_all_substrings:
        if concat(s1):
            dict_of_concat.__setitem__(s1, 0)
    return len(dict_of_concat)

In [7]:
s = 'abcabcabc'
print(all_concat(s))

3


## Объединение отрезков
Дан массив отрезков intervals, в котором intervals[i] = [starti, endi], некоторые
отрезки могут пересекаться. Напишите функцию, которая объединяет все пересекающиеся отрезки
в один и возвращает новый массив непересекающихся отрезков.

In [8]:
def unite(intervals):
    j = 0
    while j < len(intervals):
        i = 0
        while i < len(intervals):
            if intervals[i][0] < intervals[j][1] and intervals[i][1] > intervals[j][0] and intervals[i] != intervals[j]:
                if intervals[i][0] <= intervals[j][0]:
                    intervals[j] = [intervals[i][0], intervals[j][1]]
                if intervals[i][1] >= intervals[j][1]:
                    intervals[j] = [intervals[j][0], intervals[i][1]]
                intervals.pop(i)

                i -= 1
                j -= 1
            i += 1
        j += 1

In [9]:
intervals = [[1, 3], [2, 6], [8, 10], [15, 18]]

unite(intervals)

print(intervals)

[[1, 6], [8, 10], [15, 18]]


## Контрольные задачи 

### Задача 1. (Треугольник с максимальным периметром)
Массив A состоит из целых положительных чисел длин
отрезков. Составьте из трех отрезков
такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью функция
возвращает 0.

In [10]:
def puzir(arr):
    length = len(arr)
    for i in range(length-1):
        for j in range(length-i-1):
            if arr[j] < arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr


def max_per(arr):
    length = len(arr)
    for i in range(length-2):
        if arr[i]+arr[i+1] > arr[i+2] and arr[i]+arr[i+2] > arr[i+1] and arr[i+2]+arr[i+1] > arr[i]:
            per = arr[i] + arr[i+1] + arr[i+2]
            return per
    return 0

In [11]:
arr = [2, 1, 2]
print(max_per(arr))

5


### Задача 2. (Максимальное число)
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

In [12]:
import numpy
from copy import deepcopy


def biggest_first_number(row):
    ans_row = deepcopy(row)

    max = -3
    for i in range(len(row)):
        if ans_row[i][0] >= max:
            max = ans_row[i][0]
    for i in range(len(row)):
        if ans_row[i][0] != max and ans_row[i][0] >= 0:
            ans_row[i][0] = -2
    return ans_row


def add_best_numbers(row, original_row):
    big_number = ''
    isNeededToBeChecked = False

    for i in range(len(row)):
        if row[i][0] >= 0:  
            if len(row[i]) == 1:
                big_number += str(''.join(map(str, original_row[i])))
                row[i][0] = -1
            else:
                row[i].__delitem__(0)
                isNeededToBeChecked = True

    length = len(row)
    i = 0
    while i < length:  # удаляем добавленные числа
        if row[i][0] == -1:
            original_row.__delitem__(i)
            row.__delitem__(i)
            length -= 1
        else:
            i += 1

    if isNeededToBeChecked:
        best_numbers = biggest_first_number(row)
        big_number += add_best_numbers(best_numbers, original_row)
    return big_number


def find_max(row):
    length = len(row)
    big_number = ''

    raw_row = [''] * length

    for i in range(length):
        number = str(row[i])  # превращаем наши числа в массив символов
        raw_row[i] = list(number)  # записываем наш массив в массив
        raw_row[i] = [int(raw_row[i]) for raw_row[i] in raw_row[i]]

    while len(raw_row) != 0:
        best_numbers = biggest_first_number(raw_row)  # находим лучших кандидатов

        big_number += add_best_numbers(best_numbers, raw_row)

    return big_number

In [13]:
row = numpy.random.randint(1, 150, size=5)
print(row)
result = find_max(row)
print(result)

[127  66 116 104  52]
6652127116104


### Задача 3. (Сортировка диагоналей в матрице)
Дана матрица mat размером m * n, значения целочисленные.
Напишите функцию, сортирующую
каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [14]:
import numpy

def sort_matrix(mat):
    height = len(mat)
    width = len(mat[0])

    for x_start in range(1, width):
        line = []
        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            line.append(mat[y][x])
            x += 1
        #print(line)
        line.sort()
        #print(line)

        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            mat[y][x] = line[y]
            x += 1

    for y_start in range(0, height):
        line = []
        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            line.append(mat[y][x])
            y += 1
        #print(line)
        line.sort()
        #print(line)

        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            mat[y][x] = line[x]
            y += 1

In [15]:
matrix = numpy.random.randint(0, 10, size=(5,4))
print(matrix)

sort_matrix(matrix)
print(matrix)

[[6 5 8 4]
 [3 9 4 1]
 [6 0 4 1]
 [2 6 1 4]
 [0 7 1 9]]
[[4 1 1 4]
 [0 4 4 8]
 [1 1 6 5]
 [2 6 3 9]
 [0 7 6 9]]


## Задачи на дом (27 февраля)

### Задача 1.

В Тридевятом Царстве уже много лет как установилась конституционная монархия. В парламент Тридевятого царства входят 26 партий, обозначаемых строчными буквами английского алфавита от «a» до «z». Заседание парламента в соответствии с регламентом проходит по следующей схеме:
●	В начале заседания никаких законопроектов на повестке дня не стоит.
●	Любая партия (в том числе и та, которая внесла текущий законопроект) в любой момент времени может внести на обсуждение новый законопроект.
●	При вносе партией нового законопроекта обсуждение предыдущего приостанавливается и начинается обсуждение нового. После того, как парламентарии голосуют за новый законопроект, обсуждение законопроекта, прерванного им, продолжается.
●	Дискуссия по любому законопроекту обязана завершиться голосованием по этому законопроекту.
●	В конце заседания не должно остаться внесённых законопроектов, дискуссия по которым не завершена.
Вам дана запись о событиях на сессии парламента. Каждое событие является либо внесением нового законопроекта, либо голосованием за какой-то законопроект, причём в обоих случаях известен номер партии, этот законопроект предложившей. События даны в том порядке, в котором они происходили. Проверьте, может ли данная запись о событиях соответствовать какому-либо заседанию, удовлетворяющему порядку проведения, описанному выше.

In [16]:
def check(events):
    stack = []
    for e in events:
        cmd, party = e.split()
        if cmd == "Add":
            stack.append(party)
        elif stack.pop() != party:
            return "No"
    return "Yes" if len(stack) == 0 else "No"

In [17]:
check(["Add y", "Vote y"])

'Yes'

### Задача 2. Правильный подмногоугольник

Задан правильный N-угольник. Требуется выбрать наименьшее количество его вершин, которые также образуют правильный многоугольник.

In [18]:
def subpolygon(N):
    for i in range(3, int(N**.5)+1):
        if N % i == 0: return i
    if N > 4 and N % 2 == 0:
        return N / 2
    return N

In [19]:
subpolygon(12) 

3

### Задача 3.

На форуме, на котором обсуждаются задачи олимпиад по информатике, ввели следующий аналог капчи. Участнику выдаётся строка из N десятичных цифр (без ведущих нулей). В качестве ответа требуется ввести такое основание системы счисления B, что в этой системе счисления выданная запись будет соответствовать составному числу (назовем его D), а также число X, большее 1 и меньшее D, являющееся делителем D.
При этом B и X не должны превосходить 109.
По заданной строке десятичных цифр найдите любую пару чисел B и X, удовлетворяющую ограничениям, или ответьте, что решения в заданных ограничениях не существует.

In [20]:
def captcha(s):
    if len(s) == 1:
        res = [0,0,0,2,0,2,0,2,3][int(s)-1]
        if res:
            return 10, res
        return -1
    S = sum(map(int, s))
    if S == 1:
        return 10, 2
    return S + 1, S

In [21]:
captcha('10')

(10, 2)

## Вывод
Были выполнены поставленные задачи на языке программирования Python.